server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/final_project_tms
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=MyVerySecureSecretKeyForJWTTokenGenerationMustBeLongEnough256bits
jwt.expiration=60

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized

logging.level.root=INFO
logging.file.name=logs/spring-boot-log.log