create table public.user_security
(
    id       integer generated by default as identity
        constraint user_security_pk
            primary key,
    user_id  integer      not null,
    username varchar(30),
    password varchar(100) not null,
    role     varchar(20)  not null
)
    using ???;

alter table public.user_security
    owner to folksy;

create table public.users
(
    id        serial
        constraint users_pk
            primary key,
    full_name varchar(100) not null,
    phone     varchar(30)  not null,
    email     varchar(50)  not null,
    age       integer      not null,
    created   timestamp    not null,
    updated   timestamp    not null
)
    using ???;

alter table public.users
    owner to folksy;

create table public.parking_spots
(
    id             integer generated by default as identity
        constraint parking_spots_pk
            primary key,
    owner_id       integer        not null
        constraint parking_spots_users
            references public.users
            on update cascade on delete cascade,
    address        varchar(100)   not null,
    description    text           not null,
    price_per_hour numeric(10, 2) not null,
    status         varchar(20)    not null
)
    using ???;

alter table public.parking_spots
    owner to folksy;

create table public.booking
(
    id          integer generated by default as identity
        constraint booking_pk
            primary key,
    renter_id   integer
        constraint booking_user
            references public.users
            on update cascade on delete cascade,
    spot_id     integer        not null
        constraint booking_parking
            references public.parking_spots
            on update cascade on delete cascade,
    start_time  timestamp      not null,
    end_time    timestamp      not null,
    total_price numeric(10, 2) not null
)
    using ???;

alter table public.booking
    owner to folksy;

